// internal/publish/prompt_test.go
package publish

import (
	"os"
	"strings"
	"testing"
)

// Golden file (design spec §Testing strategy tier 2: "both LLM prompt
// assemblies" — triage's is phase 3's, moc cleanup's is phase 4's; this
// is publish --llm's, the THIRD and final prompt-builder package).
// Generated by Step 4 below via UPDATE_GOLDEN=1; update deliberately,
// never silently, when the prompt text intentionally changes.
func TestBuildPromptGolden(t *testing.T) {
	got := BuildPrompt("# My Note\n\nSome content.\n", "clean, modern design with good typography and readable line lengths")

	goldenPath := "testdata/prompt_golden.txt"
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatal(err)
	}
	if got != string(want) {
		t.Errorf("BuildPrompt drifted from golden file.\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// CONTRACT(vault.sh:1128): an empty guidance falls back to the default
// design guidance text.
func TestBuildPromptDefaultGuidance(t *testing.T) {
	got := BuildPrompt("content", "")
	if !strings.Contains(got, "clean, modern design with good typography and readable line lengths") {
		t.Errorf("expected default guidance text, got:\n%s", got)
	}
}

// CONTRACT(vault.sh:1138-1141): the prompt states the single-file /
// inline-everything / HTML-only-output rules.
func TestBuildPromptStatesRules(t *testing.T) {
	got := BuildPrompt("content", "custom guidance")
	if !strings.Contains(got, "custom guidance") {
		t.Error("prompt missing the custom guidance text")
	}
	lower := strings.ToLower(got)
	if !strings.Contains(lower, "self-contained") {
		t.Error("prompt missing the self-contained-HTML rule")
	}
	if !strings.Contains(lower, "inline all css and js") {
		t.Error("prompt missing the inline-CSS/JS rule")
	}
	if !strings.Contains(lower, "no markdown, no code fences") {
		t.Error("prompt missing the HTML-only-output rule")
	}
}

// CONTRACT: the full note content is embedded verbatim.
func TestBuildPromptIncludesFullContent(t *testing.T) {
	note := "# Title\n\nBody with **markdown** and a [[wikilink]].\n"
	got := BuildPrompt(note, "guidance")
	if !strings.Contains(got, note) {
		t.Error("prompt does not contain the full note content verbatim")
	}
}
