// internal/moc/prompt_test.go
package moc

import (
	"os"
	"strings"
	"testing"
)

// Golden file (design spec §Testing strategy tier 2: "both LLM prompt
// assemblies (prompt drift = silent behavior change)" — triage's is
// phase 3's; this is moc cleanup's). Generated by Step 4 below via
// UPDATE_GOLDEN=1; update deliberately, never silently, when the prompt
// text intentionally changes.
func TestBuildPromptGolden(t *testing.T) {
	got := BuildPrompt("---\ntype: moc\n---\n# MOC Test\n\n## Resources\n\n- [[Foo]] — https://example.com/foo\n", "MOC Test")

	goldenPath := "testdata/prompt_golden.txt"
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatal(err)
	}
	if got != string(want) {
		t.Errorf("BuildPrompt drifted from golden file.\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// CONTRACT(#110): forbidden/allowed operations and the JSON shape are
// stated explicitly (mirrors test_build_prompt_states_forbidden_operations
// / test_build_prompt_requests_json_shape).
func TestBuildPromptStatesContract(t *testing.T) {
	got := BuildPrompt("content", "MOC Test")
	lower := strings.ToLower(got)
	if !strings.Contains(lower, "must not delete") {
		t.Error("prompt missing the forbidden-delete rule")
	}
	if !strings.Contains(lower, "frontmatter") {
		t.Error("prompt missing frontmatter mention")
	}
	if !strings.Contains(got, `"new_content"`) || !strings.Contains(got, `"duplicates_flagged"`) {
		t.Error("prompt missing the JSON response shape")
	}
}

// CONTRACT(#110): the full MOC content is embedded verbatim (mirrors
// test_build_prompt_includes_full_moc_content).
func TestBuildPromptIncludesFullContent(t *testing.T) {
	mocText := "---\ntype: moc\n---\n# MOC Test\n\n## Resources\n\n- [[foo]] — bar\n"
	got := BuildPrompt(mocText, "MOC Test")
	if !strings.Contains(got, mocText) {
		t.Errorf("prompt does not contain full moc content verbatim")
	}
}
